# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUserForm(object):
    has_been_called = False
    def __init__(self, MainWindow):
        self._MainWindow = MainWindow
        has_been_called = False
    def setupUi(self):
        self._MainWindow.setObjectName("MainWindow")
        self._MainWindow.resize(546, 416)
        self._MainWindow.setStyleSheet("*{\n"
"    \n"
"    background-color:  rgb(22, 22, 22);\n"
"font: 25 14pt \"Bahnschrift Light\";\n"
"}\n"
"QLabel{\n"
"    color: rgb(216, 8, 36);\n"
"    margin:20px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"    border-bottom:2px solid rgb(216, 8, 36);\n"
"    color: rgb(102, 204, 0);\n"
"    margin:5px;\n"
"}\n"
"QLineEdit::hover{\n"
"    border-bottom:2px solid rgb(184, 6, 33);\n"
"    \n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"QPushButton::hover{\n"
"    \n"
"    background-color: rgb(216, 8, 36);\n"
"    \n"
"    color: rgb(22, 22, 22);\n"
"}\n"
"QPushButton{\n"
"    border:2px solid rgb(216, 8, 36);\n"
"    border-radius: 15px;\n"
"    font:22px bold ;\n"
"    color: rgb(216, 8, 36);\n"
"    \n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(self._MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self._MainWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.AddUserButton = QtWidgets.QPushButton(self.widget)
        self.AddUserButton.setMinimumSize(QtCore.QSize(0, 35))
        self.AddUserButton.setObjectName("AddUserButton")

        self.verticalLayout.addWidget(self.AddUserButton)
        self.gridLayout.addWidget(self.widget, 3, 0, 1, 2)

        self.JobInput = QtWidgets.QLineEdit(self._MainWindow)
        self.JobInput.setMinimumSize(QtCore.QSize(154, 40))
        self.JobInput.setMaximumSize(QtCore.QSize(180, 40))
        self.JobInput.setAlignment(QtCore.Qt.AlignCenter)
        self.JobInput.setClearButtonEnabled(True)
        self.JobInput.setObjectName("JobInput")

        self.gridLayout.addWidget(self.JobInput, 2, 1, 1, 1)

        self.FullNameInput = QtWidgets.QLineEdit(self._MainWindow)
        self.FullNameInput.setMinimumSize(QtCore.QSize(154, 40))
        self.FullNameInput.setMaximumSize(QtCore.QSize(180, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.FullNameInput.setFont(font)
        self.FullNameInput.setCursorPosition(0)
        self.FullNameInput.setAlignment(QtCore.Qt.AlignCenter)
        self.FullNameInput.setDragEnabled(True)
        self.FullNameInput.setPlaceholderText("")
        self.FullNameInput.setClearButtonEnabled(True)
        self.FullNameInput.setObjectName("FullNameInput")

        self.gridLayout.addWidget(self.FullNameInput, 0, 1, 1, 1)

        self.AgeInput = QtWidgets.QLineEdit(self._MainWindow)
        self.AgeInput.setMinimumSize(QtCore.QSize(154, 40))
        self.AgeInput.setMaximumSize(QtCore.QSize(180, 40))
        self.AgeInput.setAlignment(QtCore.Qt.AlignCenter)
        self.AgeInput.setClearButtonEnabled(True)
        self.AgeInput.setObjectName("AgeInput")

        self.gridLayout.addWidget(self.AgeInput, 1, 1, 1, 1)

        self.FullNameLabel = QtWidgets.QLabel(self._MainWindow)
        self.FullNameLabel.setMaximumSize(QtCore.QSize(138, 16777215))
        self.FullNameLabel.setObjectName("FullNameLabel")

        self.gridLayout.addWidget(self.FullNameLabel, 0, 0, 1, 1)

        self.AgeLabel = QtWidgets.QLabel(self._MainWindow)
        self.AgeLabel.setMaximumSize(QtCore.QSize(138, 16777215))
        self.AgeLabel.setObjectName("AgeLabel")
        self.gridLayout.addWidget(self.AgeLabel, 1, 0, 1, 1)

        self.JobLabel = QtWidgets.QLabel(self._MainWindow)
        self.JobLabel.setMaximumSize(QtCore.QSize(138, 16777215))
        self.JobLabel.setObjectName("JobLabel")
        self.gridLayout.addWidget(self.JobLabel, 2, 0, 1, 1)

        self.retranslateUi(self._MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self._MainWindow)
        # Button Behavior
        self.AddUserButton.clicked.connect(self.SEND_DATA)


    def SEND_DATA(self):
        self.age = self.AgeInput.text()
        self.name = self.FullNameInput.text()
        self.job = self.JobInput.text()
        self.has_been_called = True
        """
        if self.has_been_called == False:
            self.has_been_called = True
        else: self.has_been_called = False
        """
        return self.name,self.age,self.job

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self._MainWindow.setWindowTitle(_translate("self._MainWindow", "Form"))
        self.AddUserButton.setText(_translate("self._MainWindow", "ADD USER"))
        self.JobInput.setPlaceholderText(_translate("self._MainWindow", "eg. developper"))
        self.AgeInput.setPlaceholderText(_translate("self._MainWindow", "eg. 18"))
        self.FullNameLabel.setText(_translate("self._MainWindow", "Full Name"))
        self.AgeLabel.setText(_translate("self._MainWindow", "Age"))
        self.JobLabel.setText(_translate("self._MainWindow", "Job"))

