# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sec

class Ui_MainWindow(object):
    _Admins = {"med": "123", "sam": "1"}

    def __init__(self, MainWindow):
        self._MainWindow = MainWindow
        
    def setupUi(self):
        self._MainWindow.setObjectName("MainWindow")
        self._MainWindow.resize(437, 441)
        self._MainWindow.setStyleSheet("\n"
"*{\n"
"background-color: qradialgradient(spread:pad, cx:1, cy:0.233364, radius:0.5, fx:0.58, fy:0.4375, stop:0 rgba(149, 88, 88, 140), stop:0.102273 rgba(117, 87, 75, 255), stop:0.318182 rgba(30, 217, 255, 255), stop:0.443182 rgba(0, 198, 172, 196), stop:0.727273 rgba(47, 255, 0, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QLabel{\n"
"    background:transparent;\n"
"    color: rgb(229, 96, 66);\n"
"    font:20px Arial;\n"
"}\n"
"#UserNameFrame:hover{\n"
"    \n"
"    background-color: rgb(202, 200, 201);\n"
"    \n"
"    color: rgb(80, 79, 80);\n"
"}\n"
"#UserNameFrame\n"
"{\n"
"    border: 2px solid #d1d0d0;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(229, 227, 228);\n"
"    margin-right: 5px;\n"
"    margin-top:5px;\n"
"    margin-left:40;\n"
"    margin-right:30;\n"
"    \n"
"}\n"
"\n"
"#PasswordInputField{\n"
"   border: 0px solid #d1d0d0;\n"
"   background: transparent;\n"
"\n"
"\n"
"}\n"
"#UserInputField{\n"
"   border: 0px solid #d1d0d0;\n"
"   background: transparent;\n"
"\n"
"\n"
"}\n"
"QLineEdit{\n"
"   font: 12px Arial;\n"
"   padding:3px;\n"
"   background:transparent;\n"
"}\n"
"\n"
"#PasswordFrame:hover{\n"
"    background-color: rgb(202, 200, 201);\n"
"    \n"
"    color: rgb(80, 79, 80);\n"
"}\n"
"#PasswordFrame\n"
"{\n"
"    border: 2px solid #d1d0d0;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(229, 227, 228);\n"
"    margin-right: 5px;\n"
"    margin-top:5px;\n"
"    margin-left:40;\n"
"    margin-right:30;\n"
"    \n"
"}\n"
"\n"
"#wid{\n"
"background:transparent;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    \n"
"    \n"
"    background-color: qradialgradient(spread:pad, cx:1, cy:0.233364, radius:0.5, fx:0.58, fy:0.4375, stop:0 rgba(149, 88, 88, 140), stop:0.102273 rgba(117, 87, 75, 255), stop:0.318182 rgba(30, 217, 255, 255), stop:0.443182 rgba(0, 198, 172, 196), stop:0.727273 rgba(47, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"    border:1px solid  rgb(225, 94, 64);\n"
"    border-radius: 10px;\n"
"    \n"
"    color: rgb(49, 255, 3);\n"
"    font: 22px Tahoma;\n"
"    padding:5px;\n"
"    margin-left:25;\n"
"    margin-right:25;\n"
"    tansition: 0.8s;\n"
"}\n"
"QPushButton:active{\n"
"    \n"
"    background-color: rgb(0, 0, 61);\n"
"    \n"
"    border-color: rgb(10, 247, 231);\n"
"    \n"
"    \n"
"    color: rgb(100, 255, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(100, 255, 255);\n"
"    \n"
"    border-color: rgb(10, 247, 231);\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 61);\n"
"\n"
"}\n"
"\n"
"#title{\n"
"    color: rgb(214, 0, 61);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(self._MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.wid = QtWidgets.QWidget(self.centralwidget)
        self.wid.setMinimumSize(QtCore.QSize(1, 50))
        self.wid.setMaximumSize(QtCore.QSize(16777215, 50))
        self.wid.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wid.setObjectName("wid")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wid)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(self.wid)
        self.title.setMinimumSize(QtCore.QSize(121, 41))
        self.title.setMaximumSize(QtCore.QSize(121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        self.gridLayout.addWidget(self.wid, 0, 0, 1, 1)
        self.UserNameFrame = QtWidgets.QFrame(self.centralwidget)
        self.UserNameFrame.setMinimumSize(QtCore.QSize(230, 51))
        self.UserNameFrame.setMaximumSize(QtCore.QSize(291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(10)
        self.UserNameFrame.setFont(font)
        self.UserNameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserNameFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.UserNameFrame.setLineWidth(2)
        self.UserNameFrame.setObjectName("UserNameFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.UserNameFrame)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Image1Field = QtWidgets.QLabel(self.UserNameFrame)
        self.Image1Field.setMinimumSize(QtCore.QSize(31, 21))
        self.Image1Field.setMaximumSize(QtCore.QSize(31, 21))


        self.pixmap = QtGui.QPixmap('user-login-icon-14.png')
        self.Image1Field.setPixmap(self.pixmap)
        self.Image1Field.setScaledContents(True)
        
        self.Image1Field.setText("")
        self.Image1Field.setObjectName("Image1Field")
        self.horizontalLayout_2.addWidget(self.Image1Field)
        self.UserInputField = QtWidgets.QLineEdit(self.UserNameFrame)
        self.UserInputField.setMinimumSize(QtCore.QSize(147, 24))
        self.UserInputField.setDragEnabled(True)
        self.UserInputField.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.UserInputField.setClearButtonEnabled(True)
        self.UserInputField.setObjectName("UserInputField")
        self.horizontalLayout_2.addWidget(self.UserInputField)
        self.gridLayout.addWidget(self.UserNameFrame, 1, 0, 1, 1)
        self.PasswordFrame = QtWidgets.QFrame(self.centralwidget)
        self.PasswordFrame.setMinimumSize(QtCore.QSize(230, 51))
        self.PasswordFrame.setMaximumSize(QtCore.QSize(291, 51))
        self.PasswordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PasswordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PasswordFrame.setObjectName("PasswordFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.PasswordFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Image2Field = QtWidgets.QLabel(self.PasswordFrame)
        self.Image2Field.setMinimumSize(QtCore.QSize(31, 21))
        self.Image2Field.setMaximumSize(QtCore.QSize(31, 21))
        


        
        self.pixmap = QtGui.QPixmap('../sources images/lck2.png')
        self.Image2Field.setPixmap(self.pixmap)
        self.Image2Field.setScaledContents(True)
        
        #self.Image2Field.setStyleSheet("image: url(:/newPrefix/lck2.png);")
        self.Image2Field.setText("")
        self.Image2Field.setObjectName("Image2Field")
        self.horizontalLayout.addWidget(self.Image2Field)
        self.PasswordInputField = QtWidgets.QLineEdit(self.PasswordFrame)
        self.PasswordInputField.setMinimumSize(QtCore.QSize(147, 24))
        self.PasswordInputField.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PasswordInputField.setWhatsThis("")
        self.PasswordInputField.setAccessibleDescription("")
        self.PasswordInputField.setAutoFillBackground(False)
        self.PasswordInputField.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.PasswordInputField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PasswordInputField.setDragEnabled(True)
        self.PasswordInputField.setClearButtonEnabled(True)
        self.PasswordInputField.setObjectName("PasswordInputField")
        self.horizontalLayout.addWidget(self.PasswordInputField)
        self.gridLayout.addWidget(self.PasswordFrame, 2, 0, 1, 1)
        self.LoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoginButton.setMaximumSize(QtCore.QSize(320, 16777215))
        self.LoginButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.LoginButton.setObjectName("LoginButton")
        self.gridLayout.addWidget(self.LoginButton, 3, 0, 1, 1)
        self._MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(self._MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self._MainWindow)
        self._MainWindow.setTabOrder(self.PasswordInputField, self.UserInputField)
        self._MainWindow.setTabOrder(self.UserInputField, self.LoginButton)
        # Button Behavior
        self.LoginButton.clicked.connect(self.signin)
    def signin(self):
        try:
            if self._Admins[self.UserInputField.text()] == self.PasswordInputField.text():
                self.show_sec(self.UserInputField.text())
                print("Loged In")
            else:
                print('invalid Info')
        except KeyError:
            print("Failed To log In")
        except SyntaxError:
            print('SyntaxError')

    def show_sec(self, AdminName):
        self.Form = QtWidgets.QMainWindow()
        self.second = sec.Ui_MainWindow(self.Form,AdminName)
        self.second.setupUi()
        self.Form.show()
        
        self._MainWindow.hide()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self._MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "USER LOGIN"))
        self.UserInputField.setPlaceholderText(_translate("MainWindow", "USER NAME"))
        self.PasswordInputField.setPlaceholderText(_translate("MainWindow", "PASSWORD"))
        self.LoginButton.setText(_translate("MainWindow", "Login"))
#import source_rc

