# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sec.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import first,sqlite3,sys,addus, threading, time

class Ui_MainWindow(object):
    def __init__(self, MainWindow, AdminName):
        self._MainWindow = MainWindow
        self._AdminName = AdminName
        # Add user interface
        self.AddUserForm = QtWidgets.QWidget()
        self.adder = addus.Ui_AddUserForm(self.AddUserForm)
        self.adder.setupUi()

    def setupUi(self):
        self._MainWindow.setObjectName("MainWindow")
        self._MainWindow.resize(661, 499)
        self._MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(self._MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.AdminName = QtWidgets.QLabel(self.centralwidget)
        self.AdminName.setGeometry(QtCore.QRect(40, 20, 111, 41))
        self.AdminName.setObjectName(self._AdminName)

        self.AddUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddUserButton.setGeometry(QtCore.QRect(200, 20, 151, 51))
        self.AddUserButton.setObjectName("AddUserButton")

        self.ShowInfoButton = QtWidgets.QPushButton(self.centralwidget)
        self.ShowInfoButton.setGeometry(QtCore.QRect(360, 20, 91, 41))
        self.ShowInfoButton.setObjectName("ShowInfoButton")

        self.Logout = QtWidgets.QPushButton(self.centralwidget)
        self.Logout.setGeometry(QtCore.QRect(460, 30, 81, 31))
        self.Logout.setObjectName("Logout")

        self.ConnectToDBButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConnectToDBButton.setGeometry(QtCore.QRect(560, 30, 81, 31))
        self.ConnectToDBButton.setObjectName("Refresh")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(170, 80, 381, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(6)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self._MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(self._MainWindow)
        QtCore.QMetaObject.connectSlotsByName(self._MainWindow)
        #Buttons Behaviors
        self.Logout.clicked.connect(self.sign_out)
        self.ConnectToDBButton.clicked.connect(self.Get_Data)
        self.AddUserButton.clicked.connect(self.SHOW_ADD_USER)
        self.ShowInfoButton.clicked.connect(self.SEARCH_DATA)

    def SHOW_ADD_USER(self):
        print(self.AddUserForm.isVisible())
        self.AddUserForm.show()
        self.AddUserForm.isVisible()
        def wait():
            while self.AddUserForm.isVisible():
                if self.adder.has_been_called == True:
                    self.name,self.age,self.job = self.adder.SEND_DATA()
                    self.adder.has_been_called = False
                    #print(self.name)
                    self.INSERT_DATA(self.name, self.age, self.job)
            

        
        wait_For_Output = threading.Thread(target=wait)
        wait_For_Output.start()


    def SEARCH_DATA(self):
        c,d = self.Get_Data()
        c.execute("SELECT * FROM myNewTest_table  ")
        #WHERE full_name = 'Mohamed'
        data = c.fetchall()
        #print(data)
        self.tableWidget.setRowCount(0)
        for row_count, row_data in enumerate(data):
            self.tableWidget.insertRow(row_count)
            for n, v in enumerate(row_data):
                newItem = QtWidgets.QTableWidgetItem(v)
                self.tableWidget.setItem(row_count, n, newItem)
        #print(self.name,self.age,self.job)
                
                #print('Wiorked')
    def sign_out(self):
        self.Form = QtWidgets.QMainWindow()
        self.first = first.Ui_MainWindow(self.Form)
        self.first.setupUi()
        self.Form.show()
        self._MainWindow.hide()

    def Get_Data(self):
        B = """CREATE TABLE myNewTest_table(full_name text,age text,job text) """

        db = sqlite3.connect('myTest.db')
        cursor = db.cursor()
        
        try:

            command = ''' SELECT * from myNewTest_table '''
            result = cursor.execute(command)
            return cursor,db
            print(result)
        except:
            result = cursor.execute(B)
            return cursor,db
        
    # This For Adding New Users To DB

    def INSERT_DATA(self, name, age, job):
        c,d = self.Get_Data()
        # i want to generate huge number of users so i used this
        #l = [(x,y,z) for x in 'Hell' for y in range(2) for z in 'MED']
        #for i in l:
        if c.execute("INSERT INTO myNewTest_table VALUES ('{}','{}','{}')".format(name, age, job)):
        #print('User ',i,' Added Succesfully') 
            print('{} ADDED'.format(name))
        d.commit()




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self._MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AdminName.setText(_translate("MainWindow", self._AdminName))
        self.AddUserButton.setText(_translate("MainWindow", "Add User"))
        self.ShowInfoButton.setText(_translate("MainWindow", "Show Users"))
        self.Logout.setText(_translate("MainWindow", "Logout"))
        self.ConnectToDBButton.setText(_translate("MainWindow", "Connect"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "D"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "E"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Age"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Job"))
        


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    run = Ui_MainWindow(Form, "Mohamed")
    run.setupUi()
    Form.show()